name: Deploy-postgresql-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ...'
      - run: ls -la
      - run: touch .env
      - run: echo 'DEV_DATABASE_URL=${{secrets.PG_CONN}}' >> .env
      - run: cat .env
      - run: docker build -t helmanu/mysql-restapi-games:${{github.sha}} .
      - run: docker images
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/mysql-restapi-games:${{github.sha}}
